#!/bin/sh
#   Copyright 2015 Dan Collins & Tim Dawson
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

fail=0
for f in `git diff --cached --name-only --diff-filter=ACM`
do
    output=`cat $f | grep 'Dan Collins & Tim Dawson'`
    if [ $? == '1' ]
    then
	echo "'" $f "'" "does not have the copyright licence notice!"
        fail=1
    fi
done

if [ $fail != 0 ]
then
    exit 1;
fi
